apiVersion: apps/v1
kind: Deployment
metadata:
  name: favourite-service
  namespace: ecommerce
  labels:
    app: favourite-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: favourite-service
  template:
    metadata:
      labels:
        app: favourite-service
    spec:
      containers:
      - name: favourite-service
        image: favourite-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8800
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "stage"
        - name: SERVER_PORT
          value: "8800"
        - name: USER_SERVICE_URL
          value: "http://user-service:8700"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8800
          initialDelaySeconds: 90
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8800
          initialDelaySeconds: 60
          periodSeconds: 5
          failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: favourite-service
  namespace: ecommerce
spec:
  type: NodePort
  selector:
    app: favourite-service
  ports:
  - port: 8800
    targetPort: 8800
    nodePort: 30800
    protocol: TCP

---