---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: ecommerce
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: order-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8300
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "stage"
        - name: SERVER_PORT
          value: "8300"
        - name: PRODUCT_SERVICE_URL
          value: "http://product-service:8500"
        - name: PAYMENT_SERVICE_URL
          value: "http://payment-service:8400"
        - name: SHIPPING_SERVICE_URL
          value: "http://shipping-service:8600"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8300
          initialDelaySeconds: 90
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8300
          initialDelaySeconds: 60
          periodSeconds: 5
          failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: ecommerce
spec:
  type: NodePort
  selector:
    app: order-service
  ports:
  - port: 8300
    targetPort: 8300
    nodePort: 30300
    protocol: TCP

---